version: '3.8'

services:
  # Servicio de Base de Datos MySQL
  ticketcore-db:
    image: mysql:8.0
    container_name: ticketcore_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ticketcore_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ticketuser
      MYSQL_PASSWORD: ticketpass
    ports:
      - "3306:3306"
    volumes:

      - mysql_data:/var/lib/mysql

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: